source 'https://github.com/CocoaPods/Specs.git'

target 'JAQSliderView', :exclusive => true do
  pod "JAQSliderView", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "JAQSliderView", :path => "../"

  
end
